stages:
  download:
    cmd: bash get_1D.sh
    deps:
    - get_1D.sh
    outs:
    - raw
  decompress:
    cmd: bash bunzip2.sh
    deps:
    - bunzip2.sh
    - raw
    outs:
    - interim
  agpt:
    cmd: bash agpt.sh
    deps:
    - interim
    - agpt.sh
    outs:
    - processed_agpt
  cdvae:
    cmd: cdvae.sh
    deps:
    - interim
    - cdvae.sh
    outs:
    - processed_cdvae
  flowmm:
    cmd: bash flowmm.sh
    deps:
    - interim
    - flowmm.sh
    outs:
    - processed_flowmm

