stages:
  download:
    cmd: bash scripts/download.sh
    deps:
    - scripts/download.sh
    outs:
    - raw
  decompress:
    cmd: bash scripts/decompress.sh
    deps:
    - scripts/decompress.sh
    - raw
    outs:
    - interim
  atomgpt:
    cmd: bash scripts/atomgpt.sh
    deps:
    - interim
    - scripts/atomgpt.sh
    outs:
    - atomgpt_ehull
  cdvae:
    cmd: scripts/cdvae.sh
    deps:
    - interim
    - scripts/cdvae.sh
    outs:
    - cdvae_ehull

